name: simple_network_sim
channels:
  - defaults
dependencies:
  # install dependencies
  - python=3.7
  - networkx=2.4
  - matplotlib=3.1.3

  # test dependencies
  - coverage=5.0
  - pytest=5.4.1
  - pytest-cov=2.8.1
