name: simple_network_sim
channels:
  - defaults
  - scottishcovidresponse
dependencies:
  # install dependencies
  - python=3.7
  - networkx=2.4
  - matplotlib=3.1.3
  - pandas=1.0.3
  - data_pipeline_api=0.5.0
  - pyyaml=5.3.1
  - gitpython=3.1.3
  - git=2.23.0

  # test dependencies
  - coverage=5.0
  - pytest=5.4.1
  - pytest-cov=2.8.1
