data_directory: test_download
access_log: access-{run_id}.yaml
fail_on_hash_mismatch: True
namespace: SCRC

read:
 - where:
     data_product: human/demographics/population/scotland
     component: health_board/age/genders
   use:
     version: 1.0.0
