[symptom-probability-no-age]
type = "point-estimate"
value = 0.692

['[0,17)']
type = "point-estimate"
value = 0.21

['[17,70)']
type = "point-estimate"
value = 0.42

['70+']
type = "point-estimate"
value = 0.69